# DATA PROFILING

In [15]:
# IMPORT LIABRAIES

import pandas as pd
import numpy as np

In [11]:
# LOAD DATA

people_data = pd.read_csv(r"C:\Users\HARSHVARDHAN\OneDrive\Desktop\HR_Analytics_Project\data\raw\people_data.csv")

people_employment_history = pd.read_csv(r"C:\Users\HARSHVARDHAN\OneDrive\Desktop\HR_Analytics_Project\data\raw\people_employment_history.csv")

In [10]:
# CHECK FOR DUPLICATES

people_data.duplicated().sum()

np.int64(0)

In [9]:
# CHECK DUPLICATE EMPLOYEE_ID IN PEOPLE DATA

people_data['employee_id'].duplicated().sum()

np.int64(0)

In [17]:
# PROFILE PEOPLE DATA

people_data.head()

,employee_id,gender,race,birth_date,education,location,location_city,marital_status,employment_status
0,12104572130,Female,Caucasian,1/25/1967,Master's degree,On-site,Los Angeles,Married,Full Time
1,3381966,Female,Caucasian,12/26/1990,Bachelor's degree,Remote,Washington DC,Single,Full Time
2,12868764,Male,Caucasian,5/30/1982,Bachelor's degree,On-site,San Francisco,Single,Full Time
3,17445638,Male,Caucasian,8/5/1984,Bachelor's degree,Remote,Columbus,Single,Full Time
4,19611331,Male,African American,10/4/1990,Bachelor's degree,Remote,Washington DC,Single,Full Time

In [13]:
# CHECK FOR DUPLICATES IN EMPLOYMENT HISTORY

people_employment_history.duplicated().sum()

np.int64(0)

In [14]:
# CHECK DUPLICATE EMPLOYEE_ID IN EMPLOYMENT HISTORY

people_employment_history['employee_id'].duplicated().sum()

np.int64(0)

In [16]:
# PROFILE EMPLOYMENT HISTORY

people_employment_history.head()

,employee_id,first_name,last_name,department,sub-department,first_level_manager,second_level_manager,third_level_manager,fourth_level_manager,job_level,salary,hire_date,term_date,term_type,term_reason,active_status
0,12104572130,Kip,O'Finan,Executive,NaN,NaN,NaN,NaN,NaN,CEO,2468287,6/28/2017,NaN,NaN,NaN,1
1,3381966,Kate,Maceur,Legal,Intellectual Property,3.278384e+09,1.490362e+09,2.591261e+09,1.210457e+10,Individual Contributor,112274,12/18/2017,NaN,NaN,NaN,1
2,12868764,Bard,Kenneford,Software,Software Development,7.216768e+09,6.279119e+09,6.268712e+09,1.210457e+10,Individual Contributor,101769,3/28/2012,NaN,NaN,NaN,1
3,17445638,Saw,Sogg,Marketing,Public Relations,6.725256e+09,2.884264e+09,1.949400e+09,1.210457e+10,Individual Contributor,82641,6/29/2017,4/3/2019,Voluntary,Found a better opportunity,0
4,19611331,Cullen,Stiell,HR,Benefits,6.064345e+09,8.377150e+09,1.210457e+10,NaN,Team Lead,69487,4/12/2021,NaN,NaN,NaN,1